title: Ronalda Johnson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An experienced Software Engineer with proven proficiency in web application development and business intelligence 
  currently seeking a position as a Senior Software Developer.   Proven ability to understand and transform business
  requirements into software, ensuring applications are delivered on time, to specification, scalable and 
  maintainable. A highly-motivated individual who is always learning, able to work to tight deadlines and can communicate effectively.

  <br><br>
  <a href="https://www.linkedin.com/in/ronaldajohnson/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
